// Compiles the *.jsx sources into dist/desktop.js and dist/mobile.js.
// Run `npm run build` after editing any .jsx file, and commit dist/.
//
// The sources are plain scripts that share one global scope (e.g.
// library-screen.jsx uses MLKSVG from pages-data.jsx), so they are not
// bundled as modules: each file's JSX is compiled, the files are joined in
// load order inside a single IIFE, and the result is minified.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { transformSync } from 'esbuild';

const SHARED = [
  'tweaks-panel.jsx',
  'audio.jsx',
  'pages-data.jsx',
  'shared-hooks.jsx',
  'new-pages.jsx',
  'us-history-pages.jsx',
  'europe-history-pages.jsx',
  'greek-roman-pages.jsx',
  'egyptian-history-pages.jsx',
  'latin-american-pages.jsx',
  'japan-history-pages.jsx',
  'china-history-pages.jsx',
  'india-history-pages.jsx',
  'africa-history-pages.jsx',
  'foundational-pages.jsx',
  'next-set-pages.jsx',
  'round-14-pages.jsx',
  'round-15-pages.jsx',
  'brush-layer.jsx',
];

const ENTRIES = {
  desktop: [...SHARED,
    'library-screen.jsx',
    'coloring-screen.jsx',
    'celebration.jsx',
    'speech-game.jsx',
    'dashboard-bits.jsx',
    'dashboard.jsx',
    'app.jsx',
  ],
  mobile: [...SHARED,
    'mobile-library.jsx',
    'mobile-coloring.jsx',
    'mobile-modals.jsx',
    'mobile-app.jsx',
  ],
};

const TARGET = 'es2019'; // lowers ?. for older iPads / Chromebooks

mkdirSync('dist', { recursive: true });
for (const [name, files] of Object.entries(ENTRIES)) {
  // Compile each file separately so syntax errors point at the right file.
  const parts = files.map((file) => {
    const { code } = transformSync(readFileSync(file, 'utf8'), {
      loader: 'jsx', sourcefile: file, target: TARGET,
      jsx: 'transform', jsxFactory: 'React.createElement', jsxFragment: 'React.Fragment',
    });
    return `// ${file}\n${code}`;
  });
  const joined = `(() => {\n${parts.join('\n')}\n})();\n`;
  const { code } = transformSync(joined, {
    loader: 'js', sourcefile: `${name}.js`, target: TARGET, minify: true, charset: 'utf8',
  });
  writeFileSync(`dist/${name}.js`, `// Generated by build.mjs from the .jsx sources — do not edit.\n${code}`);
  console.log(`dist/${name}.js  ${(code.length / 1024).toFixed(0)} KB  (${files.length} files)`);
}
